### ISSUE TITLE
JavaScript syntax highlight: `this` keyword is not highlighted

### ISSUE THREAD

**Issue by iliaross** [schmittyjd/monokai-seti#124]
Hi,

Thanks for the great mod of _Monokai_ palette. By default in most palettes (including default _Monokai_) special word `this` is highlighted in red, while in _Seti_ it is not.

```JavaScript
this.property
```

Could you please fix it?

**Comment by schmty** [comment]
@rostovtsev very sorry for the late response, but I no longer spend my time maintaining this colorscheme as I do not use atom much anymore. Feel free to fork and make any changes you wish! Again, apologies for the late response.
