### ISSUE TITLE
Not displaying the Emoji

### ISSUE THREAD

**Issue by mogita** [schmittyjd/monokai-seti#18]
I have a problem under monokai-seti theme w/ seti-ui. This is a markdown document I'm working with:

<img width="182" alt="screen shot 2016-06-02 at 11 19 24" src="https://cloud.githubusercontent.com/assets/1173069/15732988/32511c0a-28b4-11e6-8bfd-7caaea31b7ab.png">

While with other themes (Base16 Tomorrow Dark for example):

<img width="197" alt="screen shot 2016-06-02 at 11 18 50" src="https://cloud.githubusercontent.com/assets/1173069/15733001/4cfcbaf0-28b4-11e6-9e04-8661a8e82fe5.png">

So it looks like the emoji characters are not visible in monokai-seti, but the markdown output is fine. Not sure if I missed anything in config?

System specs:
OS X 10.11.5
Atom 1.7.3
seti-ui 1.2.3
monokai-seti 0.7.0

**Comment by atkinchris** [comment]
@mogita - could you provide a markdown sample with an emoji that doesn't work in this theme, but works in others?
