### ISSUE TITLE
Deprecated selector in `monokai-seti/index.less` 

### ISSUE THREAD

**Issue by empirecoder** [schmittyjd/monokai-seti#21]
In `monokai-seti/index.less`:

Starting from Atom v1.13.0, the contents of atom-text-editor elements are no longer encapsulated within a shadow DOM boundary. This means you should stop using :host and ::shadow pseudo-selectors, and prepend all your syntax selectors with syntax--. To prevent breakage with existing style sheets, Atom will automatically upgrade the following selectors:

- .atom-text-editor, :host => .atom-text-editor,atom-text-editor
- .atom-text-editor .invisible-character, :host .invisible-character => .atom-text-editor .invisible-character,atom-text-editor .invisible-character
- .atom-text-editor .indent-guide, :host .indent-guide => .atom-text-editor .indent-guide,atom-text-editor .indent-guide
- .atom-text-editor .wrap-guide, :host .wrap-guide => .atom-text-editor .wrap-guide,atom-text-editor .wrap-guide
- .atom-text-editor .gutter, :host .gutter => .atom-text-editor .gutter,atom-text-editor .gutter
- .atom-text-editor .gutter .cursor-line, :host .gutter .cursor-line => .atom-text-editor .gutter .cursor-line,atom-text-editor .gutter .cursor-line
- .atom-text-editor .line-number.cursor-line-no-selection, :host .line-number.cursor-line-no-selection => .atom-text-editor .line-number.cursor-line-no-selection,atom-text-editor .line-number.cursor-line-no-selection
- .atom-text-editor .invisible, :host .invisible => .atom-text-editor .invisible,atom-text-editor .invisible
- .atom-text-editor .cursor, :host .cursor => .atom-text-editor .cursor,atom-text-editor .cursor
- .atom-text-editor .selection .region, :host .selection .region => .atom-text-editor .selection .region,atom-text-editor .selection .region
- .atom-text-editor .search-results .marker .region, :host .search-results .marker .region => .atom-text-editor .search-results .syntax--marker .region,atom-text-editor .search-results .syntax--marker .region
- .atom-text-editor .search-results .marker.current-result .region, :host .search-results .marker.current-result .region => .atom-text-editor .search-results .syntax--marker.current-result .region,atom-text-editor .search-results .syntax--marker.current-result .region
- .atom-text-editor .gfm .markup.heading, :host .gfm .markup.heading => .atom-text-editor .syntax--gfm .syntax--markup.syntax--heading,atom-text-editor .syntax--gfm .syntax--markup.syntax--heading
- .atom-text-editor .gfm .markup.underline, :host .gfm .markup.underline => .atom-text-editor .syntax--gfm .syntax--markup.syntax--underline,atom-text-editor .syntax--gfm .syntax--markup.syntax--underline
- .atom-text-editor .gfm .bold, :host .gfm .bold => .atom-text-editor .syntax--gfm .syntax--bold,atom-text-editor .syntax--gfm .syntax--bold
- .atom-text-editor .gfm .italic, :host .gfm .italic => .atom-text-editor .syntax--gfm .syntax--italic,atom-text-editor .syntax--gfm .syntax--italic
- .atom-text-editor .gfm .raw, :host .gfm .raw => .atom-text-editor .syntax--gfm .syntax--raw,atom-text-editor .syntax--gfm .syntax--raw
- .atom-text-editor .gfm .variable.list, :host .gfm .variable.list => .atom-text-editor .syntax--gfm .syntax--variable.syntax--list,atom-text-editor .syntax--gfm .syntax--variable.syntax--list
- .atom-text-editor .gfm .link, :host .gfm .link => .atom-text-editor .syntax--gfm .syntax--link,atom-text-editor .syntax--gfm .syntax--link
- .atom-text-editor .gfm .link .entity, :host .gfm .link .entity => .atom-text-editor .syntax--gfm .syntax--link .syntax--entity,atom-text-editor .syntax--gfm .syntax--link .syntax--entity
- .comment => .syntax--comment
- .string => .syntax--string
- .constant.numeric => .syntax--constant.syntax--numeric
- .constant.language => .syntax--constant.syntax--language
- .constant.character, .constant.other => .syntax--constant.syntax--character, .syntax--constant.syntax--other
- .keyword => .syntax--keyword
- .storage => .syntax--storage
- .storage.type => .syntax--storage.syntax--type
- .entity.name.class => .syntax--entity.syntax--name.syntax--class
- .entity.other.inherited-class => .syntax--entity.syntax--other.syntax--inherited-class
- .entity.name.function => .syntax--entity.syntax--name.syntax--function
- .entity.name.instance => .syntax--entity.syntax--name.syntax--instance
- .variable.parameter => .syntax--variable.syntax--parameter
- .entity.name.tag => .syntax--entity.syntax--name.syntax--tag
- .entity.other.attribute-name => .syntax--entity.syntax--other.syntax--attribute-name
- .support.function => .syntax--support.syntax--function
- .support.constant => .syntax--support.syntax--constant
- .support.type, .support.class => .syntax--support.syntax--type, .syntax--support.syntax--class
- .invalid => .syntax--invalid
- .invalid.deprecated => .syntax--invalid.syntax--deprecated
- .class.jade => .syntax--class.syntax--jade

Automatic translation of selectors will be removed in a few release cycles to minimize startup time. Please, make sure to upgrade the above selectors as soon as possible.

**Comment by atkinchris** [comment]
I have raised #22 to address this.

**Comment by dalevfenton** [comment]
Is anyone working on this issue? If not I'll try to submit a PR to fix tonight.

**Comment by atkinchris** [comment]
@dalevfenton, https://github.com/schmittyjd/monokai-seti/pull/22 already addresses this.
